# Generated by Django 5.0.6 on 2024-07-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
        ('wagtailforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedformsetting',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_settings', to='wagtailforms.form'),
        ),
    ]
