# Generated by Django 2.2.1 on 2019-05-17 19:15

import django.db.models.deletion
from django.db import migrations, models

import wagtailforms.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [("wagtailforms", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="HookSelectModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hooks",
                    wagtailforms.fields.HookSelectField(
                        blank=True, help_text="Some hooks", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvalidFormSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="ValidFormSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_settings",
                        to="wagtailforms.Form",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
